# COMMAND:
# --> gcloud deploy apply --file clouddeploy.yaml --region=us-central1 --project=dev-playground-5491
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: rust-rocket-server
description: Example Cloud Deploy flow
serialPipeline:
 stages:
 - targetId: dev-deploy
   profiles: [gcp-dev]
#  - targetId: qa-deploy
#    profiles: [gcp-qa]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: dev-deploy
description: development cluster
gke:
 cluster: projects/dev-playground-5491/locations/us-central1/clusters/shard-01
# ---
# apiVersion: deploy.cloud.google.com/v1
# kind: Target
# metadata:
#  name: qa-deploy
# description: development cluster
# gke:
#  cluster: projects/dev-playground-5491/locations/us-central1/clusters/shard-01
