apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: rocket-server
profiles:
- name: local
  portForward:
  - resourceType: deployment
    resourceName: rocket-server
    namespace: default
    port: 8000
  build:
    tagPolicy:
      inputDigest: {}
    local:
      push: true
    artifacts:
    - image: rust_rocket_server
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          # sync a single file into the `/app` folder
          - src: 'Rocket.toml'
            dest: /app
  deploy:
    kubectl:
      manifests:
        - deploy/local/*
  activation:
    - env: MAGIC_VAR=1337
    - kubeContext: kind-kind
      command: dev
- name: gcp-dev
  portForward:
  - resourceType: deployment
    resourceName: rocket-server
    namespace: dev-demo
    port: 9090
  build:
    tagPolicy:
      inputDigest: {}
    local:
      push: true
    artifacts:
    - image: rust_rocket_server
      docker:
        dockerfile: Dockerfile
  deploy:
    kubectl:
      manifests:
        - deploy/gcp/dev/*
  activation:
    - env: ROCKET_PORT=9090